### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MAX9744'

### ISSUE THREAD

**Issue by horsto** [adafruit/Adafruit_CircuitPython_MAX9744#16]
Hi, I am running into `AttributeError: 'module' object has no attribute 'MAX9744'` with the provided example code on [Adafruit QT Py RP2040](https://learn.adafruit.com/adafruit-qt-py-2040) with a fresh install of CircuitPython 8.0.3. Any ideas?

**Comment by tekktrik** [comment]
That's weird, can you go into the REPL and get the version of the library?

```
>>> import adafruit_max9744
>>> print(adafruit_max9744.__version__)
```

I'm wondering if the library is older or something else, since I don't know why the import would succeed but getting the class would fail.

**Comment by horsto** [comment]
I made a mistake here - the import was wrong / from the wrong folder/file. Closing this, since things worked fine in the end.
